### ISSUE TITLE
Feature Request: Alarm Notification on star being ready

### ISSUE THREAD

**Issue by pelletier2017** [pwatts6060/Shooting-Stars-Tracking#5]
Could you add configuration for an in-game notification that will remind you that shooting stars are about to start? It could be based on the time of the next upcoming star. I would imagine most people would want somewhere between 0 and 5 minutes notice to jump in their house or get gear to start running around. It is easy to lose track of the star timing when the next star will happen more than 1 hour from when you scout them.

I would be willing to help contribute on this or other issues.

**Comment by pwatts6060** [comment]
Fixed in version 1.0.1
![image](https://user-images.githubusercontent.com/30028569/178166399-aa4a72ad-313f-407d-8802-0ca511a24bdd.png)
You can right click a row and Add Notification/Remove notification. The orange border shows it is marked to notify you.
![image](https://user-images.githubusercontent.com/30028569/178166412-4910f5ef-c714-4a58-8f76-7405a53eec7f.png)
Notification type can be a chat message, a system tray notification, or both.
Notify percentage controls at what point in time to notify you. 0% would notify you once the minimum time is reached, 100% would notify you when the maximum time is reached. Percentages in between interpolate between the min/max time. 

I will close the issue once v1.0.1 is live
